### ISSUE TITLE
Notifications to SmartThings Hub no longer an option?

### ISSUE THREAD

**Issue by tonysurma** [excaliburpartners/HAILogger#10]
I get errors in the logs when it is posting notifications to the smartthings hub.  Looking through community posts for smartthings it appears this is no longer supported.

Does anyone else have this currently working?  Mine was working until a recent firmware update it appears.

The errors appear as:

```
OmniLinkBridge.WebAPI.WebNotification: 2019-06-08 20:42:17,678 ERROR: An error occurred sending notification to http://192.168.103.21:39500/notify/omnilink
System.Net.WebException: The operation has timed out.

```

**Comment by rwagoner** [comment]
The only issue I know of is when SmartThings broke LAN traffic to port 39500 on the hub. The workaround was to login to the SmartThings IDE, go to My Hubs, select your hub, View Utilities, and click Disconnect Hub.

I know this is a bit late, but if you're still having issues, open the SmartThings phone app, go to Automations. OmniPro, and Save the settings. This will send a command to the OmniLinkBridge and let it know your hub's new IP address.

**Comment by tonysurma** [comment]
Thanks for the comment, I dug in deep on this this weekend and I am still getting the same error.  I verified I am running the latest code versions for everything on smartthings as well as the bridge (in fact downloaded it to a new machine and configured there)

All the referenced IP's are correct as well.

"Sometimes" I get the first notification update to get back to the hub (when something happens in the OmniPro like motion etc. but then any later notifications won't go through.

Most of the time no notifications will ever get to the hub and I see those timeout errors in the log of the bridge.exe.

I don't know why I am the only one to see this.  Thanks in advance if you have any ideas.  I am a nerd but don't know of anyway to test the timeout interactively.  I am going to try to see if I can figure that out from the code for this. Thanks

**Comment by tonysurma** [comment]
FYI, I looked through the code and modified your line for testing the web api (with my IP for the hub etc.) and I get the same error when I send from the command line:

`Invoke-WebRequest -Uri "http://localhost:8000/SetUnit" -Method POST -ContentType "application/json" -Body (convertto-json -InputObject @{"id"=1;"value"=100}) -UseBasicParsing`

The same, unable to connect to remote server/timeout.  I will dig further but this worked at one point and doesn't now and there is no networking reason for it not to.

Thanks again
