### ISSUE TITLE
Unused State Topic - breaking change in HA 0.95.4

### ISSUE THREAD

**Issue by arakasi55** [excaliburpartners/HAILogger#12]
I have been seeing a warning that the unused state topics advertised by OmniLinkBridge would be a breaking change in future releases. It seems that this is as of 0.95.4 as after updating the thermostat is no longer available.

Here is the change I believe is related - [https://github.com/home-assistant/home-assistant/pull/24176](url)

![gallery_1510_6_18211](https://user-images.githubusercontent.com/51733827/60800299-52fede80-a1b8-11e9-85be-c14a096e604f.jpg)

**Comment by 5aji** [comment]
A temporary solution is to simply declare a custom climate in configuration.yaml

**Comment by rwagoner** [comment]
Thanks for the report! This has been fixed in the dev branch and will be released in 1.1.4.
