### ISSUE TITLE
schema? then Invalid range specified for mqtt_discovery_ignore_zones

### ISSUE THREAD

**Issue by txblue** [excaliburpartners/HAILogger#14]
Bravo for you work in this! v 1.1.16 worked like a champ and I should have left it alone. When updated to 1.1.7 there was a "schema" error which may have resolved by uninstall/install 1.1.7 add-in. I really don't need the extra logging (for now) from mySQL. 

Not sure if this is an issue or my problem (!)-
Now 1.1.7 fails to start for me with log message:

> Invalid range specified for mqtt_discovery_ignore_zones

That info is in the omnilink.ini file and should be null.  What am I missing? override?

**Comment by rwagoner** [comment]
I was trying to simplify the script to write out the OmniLinkBridge.ini, but have introduced a bug if not all options are defined. In the Hass.io add-on configuration add the following and you should be good to go.

"mqtt_discovery_ignore_zones": ""
"mqtt_discovery_ignore_units": ""

**Comment by rwagoner** [comment]
I think I've gotten the configuration issues all sorted out with version 1.1.8. Let me know if you're still have issues.

**Comment by txblue** [comment]
Thanks, 'cause the validate will not allow adding the "mqtt_discovery_ignore…" - at least that I can resolve [easily].

**Comment by txblue** [comment]
HAI controller is not changing its data when sent to it. This worked in 1.1.6. In this request I changed the heat call down from 67 to 63. It appears message sent, rec'd, but not acted upon.

> OmniLinkBridge.MQTT.MessageProcessor: 2019-12-28 15:38:51,314 DEBUG: Received: Type: thermostat, Id: 2, Command: temperature_heat_command, Value: 63.0
OmniLinkBridge.MQTT.MessageProcessor: 2019-12-28 15:38:51,326 DEBUG: SetThermostatHeatSetpoint: 2 to 63.0F(114)
OmniLinkBridge.MQTT.MessageProcessor: 2019-12-28 15:38:51,336 DEBUG: Received: Type: thermostat, Id: 2, Command: temperature_cool_command, Value: 72.0
OmniLinkBridge.MQTT.MessageProcessor: 2019-12-28 15:38:51,337 DEBUG: SetThermostatCoolSetpoint: 2 to 72.0F(124)
OmniLinkBridge.Modules.LoggerModule: 2019-12-28 15:38:55,104 DEBUG: ThermostatStatus 2 GR tstat 2, Status: 70 OFF, Heat: 63, Cool: 72, Mode: HEAT, Fan: AUTO, Hold: ON
OmniLinkBridge.Modules.OmniLinkII: 2019-12-28 15:38:55,112 DEBUG: Unsolicited status received for Thermostat GR tstat 2
OmniLinkBridge.Modules.LoggerModule: 2019-12-28 15:38:55,910 DEBUG: ThermostatStatus 2 GR tstat 2, Status: 70 OFF, Heat: 63, Cool: 72, Mode: HEAT, Fan: AUTO, Hold: ON
OmniLinkBridge.Modules.OmniLinkII: 2019-12-28 15:38:55,944 DEBUG: Unsolicited status received for Thermostat GR tstat 2
OmniLinkBridge.Modules.LoggerModule: 2019-12-28 15:38:57,113 DEBUG: ThermostatStatus 2 GR tstat 2, Status: 70 OFF, Heat: 67, Cool: 72, Mode: HEAT, Fan: AUTO, Hold: ON
OmniLinkBridge.Modules.OmniLinkII: 2019-12-28 15:38:57,120 DEBUG: Unsolicited status received for Thermostat GR tstat 2

**Comment by txblue** [comment]
![Annotation 2019-12-28 155405](https://user-images.githubusercontent.com/45334260/71549895-e5738400-298a-11ea-93b3-732e0f49481e.jpg)

**Comment by rwagoner** [comment]
What thermostat are you using? I have two OmniStat2 thermostats connected with Zigbee and can't replicate this issue. Between version 1.1.6 and 1.1.8 the only changes were for loading settings in relation to the Hass.io plugin. Once the MQTT command is received I'm using the official HAI C# SDK to actually send the command to the controller. I'd be interested in what happens if you send the temperature command using PC Access.

**Comment by txblue** [comment]
Hardwired OmniStat1 and hardwired OmniStat2. The C# should work. [It does, see below for exception.]

Is there an internal docker (e.g. 17.x.x.x) address for config mqtt_server? I use the network IP because it worked but tried localhost, 17.....,  and 127....: 

> "mqtt_enabled": true,
  "mqtt_server": "192.168.1.171",
  "mqtt_port": 1883,

**Control action results**
Using PC Access the action was just like the add-on as far as changing setpoint- so there is a different problem- not an add-on problem.  Changing MODE etc. work. Sorry to raise this flag. 

Sending the temperature command by either methods (pca/ha) gets a reply back with **new** set point then **reverts** to original set point. 

I had previously rebooted the controller. Guess it may be time to reboot the thermostats since they are powered by HVAC system. 

![Annotation 2019-12-29 082832](https://user-images.githubusercontent.com/45334260/71558130-3e87fa00-2a15-11ea-9194-908a0afb63cf.jpg)

![Annotation 2019-12-29 084411](https://user-images.githubusercontent.com/45334260/71558319-6d9f6b00-2a17-11ea-9fdd-b73bcd49ed01.jpg)

![Annotation 2019-12-29 083038](https://user-images.githubusercontent.com/45334260/71558152-8ad33a00-2a15-11ea-89da-c8d7044a3ae5.jpg)

**Comment by txblue** [comment]
My broker is 
> mqtt:
    broker: 172.17.0.1

**Comment by rwagoner** [comment]
Check if the thermostat is set to hold. If I remember you can’t remotely change the temp when it is on hold.

**Comment by rwagoner** [comment]
I just looked at your logs again and that’s defiantly the issue.

**Comment by txblue** [comment]
I am embarrassed.  Just discovered that via snaplink.
![Screenshot_20191229-210738_SnapLink](https://user-images.githubusercontent.com/45334260/71566865-b6d7d500-2a80-11ea-866d-c07ef1c311cf.jpg)
![Screenshot_20191229-210853_SnapLink](https://user-images.githubusercontent.com/45334260/71566874-c820e180-2a80-11ea-9d50-8ebb8c4609b1.jpg)

**Comment by txblue** [comment]
Many thanks for your help and patience.
