### ISSUE TITLE
No audio zones

### ISSUE THREAD

**Issue by madmen2302** [excaliburpartners/HAILogger#17]
It would be a fantastic feature to include audio zones and controls from devices like the HI FI 2

**Comment by edkhader** [comment]
That would be awesome.

**Comment by cjquinton2001** [comment]
how do i get the bridge to communicate with the omni?


This email is confidential and may be legally privileged.

It is intended solely for the addressee. Access to this email by anyone else, unless expressly approved by the sender or an authorized addressee, is unauthorized.

If you are not the intended recipient, any disclosure, copying, distribution or any action omitted or taken in reliance on it, is prohibited and may be unlawful. If you believe that you have received this email in error, please contact the sender, delete this e-mail and destroy all copies.
 

    On Monday, August 17, 2020, 04:10:53 PM PDT, madmen2302 <notifications@github.com> wrote:  
 
 


It would be a fantastic feature to include audio zones and controls from devices like the HI FI 2

**Comment by rwagoner** [comment]
Thanks using OmniLinkBridge! Unfortunately I'm not planning on adding audio zone support. Partly due to not having a system with audio zones to test with and also due to Leviton discontinuing the OmniPro systems.
