### ISSUE TITLE
NTP 

### ISSUE THREAD

**Issue by edkhader** [excaliburpartners/HAILogger#18]
Great app!! Please add an option in the .ini file to point it to an NTP server. I run it as a container, whenever I turn time sync on its synced to the wrong time and seems many time zones off. Thank you

**Comment by rwagoner** [comment]
Check that your docker host has the correct time and you are mounting `/etc/localtime` into your container. If the time is correct in the container the time sync will function. Adding NTP would require more than just adding a setting to the ini file.
