### ISSUE TITLE
Unit Scene Switch

### ISSUE THREAD

**Issue by jrdrake4** [excaliburpartners/HAILogger#19]
I have the UPB Unit Scene switches which can be set to On, Off, A, B, C, D.  The scene is technically a link of multiple individual units at certain dimmer percentages. 
I am using the docker install of omnilink-bridge, which when looking at the docker logs as: DEBUG: UnitStatus 1 Greatroom, Status: SCENE D

These only show up from MQTT as a Simple ON or OFF. All of the scenes simple show as ON. This was observed using MQTT Explorer.

**Comment by rwagoner** [comment]
At my previous house I used UPB switches and scenes, so I am familiar with how they work.  However, I don't currently have a system with UPB to test. For units I map the OmniLink II protocol Status byte to the MQTT state. Unfortunately, the debug output comes from the HAI C# SDK StatusText property. I don't have access to their Status to StatusText mapping. 

In looking at the OmniLink II protocol it appears that the UPB scenes A-L are indicated by values 2-13. If you could confirm this by modifying the debug output and posting the output here I can add this feature. I'm thinking it should be a separate MQTT topic scene_state

```
Modules/LoggerModules.cs function Omnilink_OnUnitStatus line 270 change 
from
 log.Verbose("UnitStatus {id} {name}, Status: {status}", e.ID, e.Unit.Name, status);
to
 log.Verbose("UnitStatus {id} {name}, Status: {status}", e.ID, e.Unit.Name, e.Unit.Status);
```

**Comment by rwagoner** [comment]
I just realized the change I posted is for the dev branch. Below is the change for the current master branch

```
Modules/LoggerModules.cs function Omnilink_OnUnitStatus line 269 change 
from
  log.Debug("UnitStatus " + e.ID + " " + e.Unit.Name + ", Status: " + status);
to
  log.Debug("UnitStatus " + e.ID + " " + e.Unit.Name + ", Status: " + e.Unit.Status);
```

**Comment by rwagoner** [comment]
I've added unit scene support to the dev branch. It appears to work from the testing I've done with PC Access, however I don't have any UPB switches to do a real test. I'll release version 1.1.9 in the next few days.
