### ISSUE TITLE
Thermostat modes discovery and reporting

### ISSUE THREAD

**Issue by netfriend85** [excaliburpartners/HAILogger#21]
Hi, 
Thank you for creating this great add-on. It brought a new life to my OmniPro II and my integration with HomeAssistant.

 
I have used the Windows installer and recently moved to the Hass.io add-on communicating to my OmniPro II via MQTT. 
My OmniPro II is using RC2000 thermostat configured in 'Heat-only' mode. 
On the RC2000 only "Off" and "Heat" modes are present.

The OmniLink-Bridge messages from the OmniPro II report "hvac_modes: auto, off, cool, heat" modes.
The presence of 'cool' mode enforces showing cooling temperature and cooling controls in HA. 

Can the OmniLink-Bridge be configured to read the thermostat modes as configured in the OmniPro II (ignoring and not showing the cool mode in this case)? 

Regards,

**Comment by rwagoner** [comment]
The thermostat type hadn't crossed my mind as I'm using all OmniStat2 thermostats with auto heat cool. I added support to the dev branch to read the thermostat type and only show the modes supported. I'll release version 1.1.9 in the next few days.

**Comment by netfriend85** [comment]
Thank you so much for the update and for your time. 
With the change to 1.19, the HomeAssistant integration now reports only the configured Thermostat modes as expected. Thank you. 

With the Thermostat modes being reported correctly, is is possible for the 'target-temp_high' to be suppressed (not being reported) to HomeAssistant matching the Thermostat modes (in this case using 'Off'/'Heat' only modes)?

![Omnistat-HA-Modes](https://user-images.githubusercontent.com/73378283/100327649-6878d200-2f80-11eb-97ff-26ff6d608887.JPG)

When using the Home Assistant add-on and when the HAI Thermostat is configured in 'Off'/'Heat' only modes, the 'target-temp_high' attribute is being reported to Home Assistant.
The reporting of the 'target-temp_high' to Home Assistant forces the Home Assistant Thermostat Card to show both temperatures (Cooling an and Heating setpoints) as controllable and it creates confusion.

I haven't found a way to make HomeAssistant to suppress and ignore the cooling setpoint nor a way to remove it from the OmniPro.

![Omnistat-Dual-Temps](https://user-images.githubusercontent.com/73378283/100328181-1a180300-2f81-11eb-92f6-13ec1324f671.JPG)




Thank you again for the great integration.
