### ISSUE TITLE
Can't set emergency heat mode via MQTT

### ISSUE THREAD

**Issue by slbailey** [excaliburpartners/HAILogger#24]
I'm using this docker in concert with Home Assistant.  Everything is working perfectly except my thermostat has the ability to enter emergency heat mode (which I can apparently do through a web service call).

I'd like to be able to do this via MQTT and Home Assistant but the only options I see are heat, cool, dry, fan only, off.

**Comment by rwagoner** [comment]
Interestingly in PC Access when I set my OmniStat2 ZigBee connected thermostat mode to emergency heat, no change occurs on the thermostat. PC Access does show emergency heat, but will revert to the previous mode a few minutes later. Additionally the Home Assistant [MQTT HVAC](https://www.home-assistant.io/integrations/climate.mqtt/#modes) integration doesn't support emergency heat. Regardless I did go ahead and add the ability to send e_heat to mode_command to change to emergency heat in the 1.1.11 release.
