### ISSUE TITLE
"Friendly names" for "System" components have a leading space

### ISSUE THREAD

**Issue by eddyg** [excaliburpartners/HAILogger#26]
Just noticed there's a leading space in the "friendly name" for all the "System" entities:

```
friendly_name: ' System AC'
friendly_name: ' System Battery'
friendly_name: ' System DCM'
friendly_name: ' System Phone'
```

Obviously a minor issue, but figured I'd mention it in case it's an easy fix.

**Comment by rwagoner** [comment]
Thanks for the report. The leading space has been correct in version 1.1.11.
