### ISSUE TITLE
.Net 5 version

### ISSUE THREAD

**Issue by IvanFarkas** [excaliburpartners/HAILogger#28]
Do you have a .Net 5 version? If not, do you need help?

**Comment by rwagoner** [comment]
Unfortunately the underlying HAI.Controller.dll is in .NET Framework.. To switch to .NET 5 would required a rewrite of that library as the source is not available. With OmniLinkBridge working under Mono and Leviton discontinuing the OmniPro controllers I don't have any plans to do this.
