### ISSUE TITLE
[Enhancement Request] Publish Last Event Log Message/Send Passcode

### ISSUE THREAD

**Issue by swamiller** [excaliburpartners/HAILogger#29]
I have been an openHAB user for some time now, mainly because there has been a binding available for my omnipro.  

I started tinkering with latest Home Assistant and there are lots of things I like better. I loaded OmniLinkBridge and it works great with Home Assistant but I am missing 2 key pieces of functionality that I was able to get from openHAB.  OpenHAB provides the last notification from the event log and also has the ability to pass a user code to the omnipro panel.

My use cases are related to messaging using the event log information (ex: user that just disarmed the system) as well as passing a user code from openHAB back to the panel so I know who armed/disarmed the system from openHAB.  I also would like the ability to use a keypad widget on a touchscreen to enter a user code.

I've considered leaving openHAB up and maybe passing this data from openHAB to Home Assistance using MQTT but I was wondering if there is any desire to add these two parameters to OmniLinkBridge?

**Comment by rwagoner** [comment]
The security code to arm/disarm has been added in version 1.1.13. You will want to set OmniLinkBridge.ini mqtt_discovery_area_code_required= to a list of the area ids you would like Home Assistant to require a security code for. 

The event log has to be polled for updates. At this time I don't have plans to add support for it.
