### ISSUE TITLE
Strike question...

### ISSUE THREAD

**Issue by TooUnCool** [excaliburpartners/HAILogger#3]
...I worked it out. It seems it doesn't work for an Omni IIe? You did mention Pro in the documentation, so it's hardly a complaint, but thought it worth a try!

Thanks
Marc

**Comment by mikec85** [comment]
I have a fork that works with Omni IIe , logs to Mqtt and accepts commands from Mqtt.

**Comment by rwagoner** [comment]
The latest version contains a fix in the connection code that should allow it to work with the Omni IIe.
