### ISSUE TITLE
FR: use `arming` state instead of `pending` with Home Assistant

### ISSUE THREAD

**Issue by eddyg** [excaliburpartners/HAILogger#30]
According to Home Assistant's [Alarm Control Panel](https://developers.home-assistant.io/docs/core/entity/alarm-control-panel/) docs, the `pending` state indicates that the alarm system is on its when to `triggered`. Right now, when the Omni alarm is set and the exit delay starts, I get a notification that the state has changed from `disarmed` to `pending`. It would be nice if the state was `arming` during the exit delay, to better match the states in Home Assistant.

Thanks again for maintaining this bridge!

**Comment by rwagoner** [comment]
Sorry for the late reply. The `arming` state was corrected for the 1.1.0 release back in July.
