### ISSUE TITLE
Problems getting this working with HA

### ISSUE THREAD

**Issue by ifuchs** [excaliburpartners/HAILogger#32]
I am new to HA and I would like to connect HA with my OmniPro. I installed the add-in in HA and configured it such that it seems to be able to see devices on the Omni (at least based on what I see in the log). The question is how do I use this integration in HA? Is there a UI that will now show me the Omni device status?

**Comment by grantalewis** [comment]
I believe this post will get you moving you in the right direction:

http://cocoontech.com/forums/topic/31314-omnilinkbridge-to-integrate-home-assistant-smartthings-node-red/page-37#entry273564

There are several of us OLB users who are active on the Cocoontech forum. You might want to create an account and hang out there while you're "getting your sea legs."

**Comment by ifuchs** [comment]
Thanks. I installed the MQTT broker as well but I am still "out to sea" (to borrow your metaphor). I will check out the Cocoontech thread.

**Comment by ifuchs** [comment]
FWIW, this is my OLB config:

```controller_address: [IP]
controller_port: [port]
controller_key1: [key1]
controller_key2: [key2]
controller_name: OmniLinkBridge
time_sync: false
time_interval: 60
time_drift: 10
verbose_unhandled: true
verbose_event: true
verbose_area: true
verbose_zone: true
verbose_thermostat_timer: true
verbose_thermostat: true
verbose_unit: true
verbose_message: true
webapi_enabled: false
webapi_port: 8000
mqtt_enabled: false
mqtt_server: ''
mqtt_port: 1883
mqtt_username: ''
mqtt_password: ''
mqtt_prefix: omnilink
mqtt_discovery_prefix: homeassistant
mqtt_discovery_name_prefix: ''
mqtt_discovery_ignore_zones: ''
mqtt_discovery_ignore_units: ''
mqtt_discovery_override_zone: ''
notify_area: false
notify_message: false
mail_server: ''
mail_tls: false
mail_port: 25
mail_username: ''
mail_password: ''
mail_from: ''
mail_to: ''
prowl_key: ''
pushover_token: ''
pushover_user: ''
```

**Comment by ifuchs** [comment]
Got it working after making several changes to the config file (and adding a username/password for mqtt broker).
