### ISSUE TITLE
[Enhancement Request] Omni Connection using Serial

### ISSUE THREAD

**Issue by pdkwork** [excaliburpartners/HAILogger#34]
My Omni IIe ethernet connection is not working and with the end of life for this product, I don't think it can be fixed.  I would like to use the serial port with a pi and this software to provide a link to Home Assistant.  I think you are using the HAI developed link that I also thought could be connected using the serial port on the Omni.

**Comment by rwagoner** [comment]
Serial used the Omni-Link protocol and ethernet used the Omni-Link II protocol. It would require a major development / testing effort to add the serial capability. If you look at the HAI SDK sample project they check HAC.Connection.ConnectionProtocol() == enuOmniLinkProtocol.V1 and go down a different logic flow for certain operations. You also have to check HAC.OkToPoll as the original Omni-Link protocol is not stateless.
