### ISSUE TITLE
Set up for ARM platform (Raspi)

### ISSUE THREAD

**Issue by robot-army** [excaliburpartners/HAILogger#37]
Hi, 

Would it be possible to make this more platform agnostic, in order that it could run on ARM/Raspberry pi?

I'm going to have a poke at trying to do it but I doubt I'll have much luck. 

R

**Comment by rwagoner** [comment]
OmniLinkBridge will run on ARM using the mono framework. You just need to install mono and download the OmniLinkBridge binary from the [releases ](https://github.com/excaliburpartners/OmniLinkBridge/releases) page. Check out the Home Assistant addon [Dockerfile](https://github.com/excaliburpartners/hassio-addons/blob/master/omnilink-bridge/Dockerfile).

**Comment by robot-army** [comment]
OK!

1) I installed mono-devel from here: https://www.mono-project.com/download/stable/#download-lin-raspbian
2) Download the binary as you suggested (mkdir, wget, unzip as needed )
3) Edit `OmniLinkBridge.ini` adding the IP address and keys for the controller
4) Run `mono OmniLinkBridge.exe -i` and, I see output!

Amazing.
Thanks!
