### ISSUE TITLE
Thermostat does not set temperature via Alexa integration 

### ISSUE THREAD

**Issue by ZacFranken** [excaliburpartners/HAILogger#38]
On issuing an “Alexa set temperature to 75” command Alexa will respond:
“The heating is keeping the temperature around 75 and between 73 and 77.”
73 is the heating setpoint and 77 is the cooling setpoint 
The heating setpoint does not get updated.
Please let me know if you need any debug information or if you would like me to run any tests.
Great addition btw.
thanks!

**Comment by rwagoner** [comment]
The Alexa thermostat capability has always seemed a bit limited. From what I've read there is no way to specify which setpoint to change in auto mode. This [EcoNet Alexa Quick Commands](https://rmc-cdn.s3.amazonaws.com/site/ruuddotcom/resources/econetsmartthermostat/pdf/RHM4959_Ruud_AlexaCommands_r3.pdf) guide lists phrases that Alexa will understand. 

Either way if there was some improvements that could be made, it would be in the Home Assistant Alexa integration. The flow is Alexa -> Home Assistant -> MQTT -> OmniLinkBridge -> HAI Controller. OmniLinkBridge isn't aware of Alexa and just receives the MQTT commands that Home Assistants.

**Comment by ZacFranken** [comment]
Thanks for the info. FYI the thermostat is in heat only mode. I’ll have a poke around in home assistant. Thanks!
