### ISSUE TITLE
MQTT "hold_" topics are being deprecated

### ISSUE THREAD

**Issue by eddyg** [excaliburpartners/HAILogger#43]
I'm receiving these deprecation warnings, and I _think_ they're coming from the **(awesome!)** OminLinkBridge:

```
The 'hold_command_topic' option is deprecated, please remove it from your configuration
The 'hold_state_topic' option is deprecated, please remove it from your configuration
The 'hold_modes' option is deprecated, please remove it from your configuration
```

My understanding is that `preset_modes` and topics now replace the `hold` modes, so `hold` is just another `preset_mode` now?

https://github.com/home-assistant/core/blob/dev/homeassistant/components/mqtt/climate.py#L813-L822

Just wanted to bring this up in hopes of getting it addressed before the deprecation deadline.

_Thanks for the great integration!_

**Comment by rwagoner** [comment]
Thanks for the heads up! I've made this change on the dev branch and will include it in the next release.
