### ISSUE TITLE
Refreshing entities on Home Assistant

### ISSUE THREAD

**Issue by WorldOfMaze** [excaliburpartners/HAILogger#44]
Since I have first installed OmniLinkBridge, my OmniPro configuration has changed.  Hence, there are entities in HA that no longer exist and entities missing that have recently added.

Is there a way to ask OmniLinkBridge to pull the new configuration from the OP II panel?

Thanks.

**Comment by grantalewis** [comment]
I believe what's going on here is that you need to (a) use something like MQTTExplorer to purge all OmniLink Bridge topics and messages from MQTT, (b) reboot the server that's running your MQTT broker, and if Home Assistant is running on a server independent of your MQTT broker (c) reboot that too. Home Assistant will then get a refreshed slate of MQTT topics/messages (entities) related to OLB from the broker.

**Comment by rwagoner** [comment]
Have you restarted OmniLinkBridge and then restarted Home Assistant after making the changes to the OmniPro? When OmniLinkBridge starts it queries the OmniPro for all entities and publishes the discovery info to MQTT. It will clear the discovery topics for entities no longer configured. I also have to restart Home Assistant for some changes to appear.
