### ISSUE TITLE
Raspberry Pi Installation Issues

### ISSUE THREAD

**Issue by PathfinderFan** [excaliburpartners/HAILogger#45]
I downloaded the binary for OmniLinkBridge onto my Raspberry Pi and got everything setup.  I had to go download mono but I was able to get the executable to run.  I followed the instructions and modified the service file as required but when I run the enable command and then check the status of the service, the output says it's inactive and so it never runs.  I've tried many different things to get it to work but I'm stuck.

**Comment by rwagoner** [comment]
The service file included requires the OmniLinkBridge.exe and related files to be located under /opt/OmniLinkBridge. Alternatively there is a docker package now available for Raspberry Pi (arm/v7), which is how I run it.
