### ISSUE TITLE
Possible to pass a device_class parameter in the MQTT discovery topic

### ISSUE THREAD

**Issue by madasus** [excaliburpartners/HAILogger#47]
Is it possible to include a device_class parameter in the zone config so that we can identify if the zone is a motion,window,door,freeze etc?

It looks like HA is currently identifying the correct class by the icon, "mdi:walk" for example for motions.  It would be useful for filtering if we could pass the device_class through as well (in this case device_class=motion)

Thank you

**Comment by rsw686** [comment]
Yes you can override a device_class in the OmniLinkBridge.ini. Please see the example below to override zone 5 as a motion and 6 as a window.

```
# device_class must be battery, door, garage_door, gas, moisture, motion, problem, smoke, or window
mqtt_discovery_override_zone = id=5;device_class=motion
mqtt_discovery_override_zone = id=6;device_class=window
```

**Comment by madasus** [comment]
Ah thanks - i'll give it a go.  I though it might be possible to read it directly from the HAI panel - but then I looked in the panel and realized that it isn't defined in the panel so that wouldn't be possible.

**Comment by rwagoner** [comment]
It attempts to map the zone type as follows. The override is needed as Home Assistant has more device classes than the OmniPro has zone types.

```
                    case enuZoneType.EntryExit:
                    case enuZoneType.X2EntryDelay:
                    case enuZoneType.X4EntryDelay:
                        ret.device_class = BinarySensor.DeviceClass.door;
                        break;
                    case enuZoneType.Perimeter:
                        ret.device_class = BinarySensor.DeviceClass.window;
                        break;
                    case enuZoneType.Tamper:
                        ret.device_class = BinarySensor.DeviceClass.problem;
                        break;
                    case enuZoneType.AwayInt:
                    case enuZoneType.NightInt:
                        ret.device_class = BinarySensor.DeviceClass.motion;
                        break;
                    case enuZoneType.Water:
                        ret.device_class = BinarySensor.DeviceClass.moisture;
                        break;
                    case enuZoneType.Fire:
                        ret.device_class = BinarySensor.DeviceClass.smoke;
                        break;
                    case enuZoneType.Gas:
                        ret.device_class = BinarySensor.DeviceClass.gas;
                        break;
```

**Comment by madasus** [comment]
Hmm.  Thats interesting.  I'm looking at the MQTT discovery msg for a "NightInt" zone and there doesn't appear to be a class sent in the spec? is it sent somewhere else?

TOPIC: homeassistant/sensor/omnilink/zone122/config

{"icon":"mdi:walk","value_template":"{{ value|replace(\"_\", \" \")|title }}","unique_id":"omnilinkzone122","name":"Sunroom Motion","state_topic":"omnilink/zone122/state","availability_topic":"omnilink/status","device":{"identifiers":"omnilink","name":"omnilink","sw_version":"0.0 - OmniLinkBridge 1.1.13.0","model":"OmniPro II","manufacturer":"Leviton"}}

**Comment by rwagoner** [comment]
Check the binary_sensor discovery topic. The sensor has a different set of supported device classes. Currently only the binary_sensor supports override the device_class. The sensor maps the zone type to an icon.

**Comment by madasus** [comment]
ah - i wondered why I had both.  Thanks.  I'll close this.

**Comment by rwagoner** [comment]
The binary_sensor provides an open/closed status. The sensor will show bypassed, tripped, armed, trouble, not_ready, and secure. I use the binary_sensor for most things and the sensors are used on a security dashboard showing zone arm status.
