### ISSUE TITLE
Audio support?

### ISSUE THREAD

**Issue by glassbase** [excaliburpartners/HAILogger#5]
Does this support audio zones and sources? 

Great work on this. This is definitely what I have been looking for to convert my dad's house to HA.

**Comment by rwagoner** [comment]
Glad to hear it is being used! Unfortunately there is no audio support.  I don’t have an audio system to test with and Home Assistant doesn’t have MQTT audio support. What audio system does he have?

**Comment by glassbase** [comment]
Russound CAV6.6. 

Will use the Russound HA integration in the future but I will have the order a serial adapter.

**Comment by glassbase** [comment]
Successfully set this up with MQTT and HA. Working with Lumina Pro controller with UPB lighting, HAI Omni thermostats and DSC security.

**Comment by mjcumming** [comment]
Hi @rwagoner, I would be interested in helping add audio support if that interests you. I have worked with OmniLink protocol before developing a plugin in Lua. 

Mike

**Comment by rwagoner** [comment]
Sure adding audio support would be great. I don’t have any audio zones, so I won’t be able to help test. However if you get it working I can merge the code.
