### ISSUE TITLE
Application time does not match actual time

### ISSUE THREAD

**Issue by mdedonato** [excaliburpartners/HAILogger#51]
Sometime in the last few builds, I noticed that the time my omnipro was being synced to was off by 4 hours.  I also noticed that all of the log file times are offset by the same amount.  Did someone change something to do with time zones recently?  I am using the latest version, but noticed the problem about a week ago.

**Comment by rwagoner** [comment]
OmniLink Bridge uses the local system time. How are you running it? Home Assistant? Docker?

**Comment by mdedonato** [comment]
I'm using it with home assistant via the addon.  The odd part is that only this addon seems to have the wrong time stamp.  The system time is correct, and all other add-ons have the correct time in their logs.

**Comment by mdedonato** [comment]
I am in the eastern time zone, so it looks like everything is being set to utc time.

**Comment by rwagoner** [comment]
I was able to replicate this. Strangely the TZ environment variable was not available in the container until I would exec in to a bash shell. Switching over to the S6 overlay used in the hassio-addons example seems to have resolved it. Please update to version 1.1.14.1 of the add-on.

**Comment by mdedonato** [comment]
Thanks!  I will give it a try

**Comment by mdedonato** [comment]
That worked, Thank you for the quick fix, and thank you for developing this app.  It works great!
