### ISSUE TITLE
Monitor Zones in HA

### ISSUE THREAD

**Issue by rlust** [excaliburpartners/HAILogger#55]
How do I monitor the zones in Home Assistant? 
I want the doors to turn on lights when opened.

**Comment by rwagoner** [comment]
Zones are added as binary sensors in Home Assistant. In Home Assistant go to Developer tools, States tab, and look for binary_sensor.omnilink. Settinsgs, Automations & scenes can be used to setup trigger for that sensor to perform the light.turn_on action.

**Comment by rlust** [comment]
Thanks so much!  Your work on this plugin is so helpful. Made my day!
