### ISSUE TITLE
Locks don't seem to be handled?

### ISSUE THREAD

**Issue by GENnetuk-DEV** [excaliburpartners/HAILogger#56]
```
2023-12-02 13:51:51 [OmniLinkBridge.Modules.OmniLinkII DBG] Unhandled ExtendedStatusAccessControlLock 33 8 59 15 5 0 2 1 0 0 138 74 
2023-12-02 13:52:04 [OmniLinkBridge.Modules.OmniLinkII DBG] Unhandled ExtendedStatusAccessControlLock 33 8 59 15 5 0 2 0 0 0 219 138 
```

There seems to be no support for Omni Locks, which means we can't see an unlock or lock or control locks to unlock or lock both of which would be really useful.

**Comment by jlipsit** [comment]
I too would be interested in getting support for Locks and Audio.

**Comment by GENnetuk-DEV** [comment]
This repo doesn't seem to be maintained any more, last update was 2 years ago. However, I have found a work-around for locking/unlocking my locks using HA. If you create a button in OmniPro and then have that button unlock a door, another button to lock, etc, then you can call those buttons via HA and do the lock/unlock. You can't get the status though which is a shame. Audio may be something that can be handled the same way with buttons, but I don't have that so I can't be sure.

**Comment by rwagoner** [comment]
The main reason for the lack of development is due to Leviton discontinuing the OmniPro product line after buying HAI in 2019. Additionally, my OmniPro II panel does not have locks or audio zones so I'm unable to test those features.

That being said, I did take a stab at implementing lock support and pushed it to the dev branch. If you're able to test, we should be able to get it working.

**Comment by GENnetuk-DEV** [comment]
> The main reason for the lack of development is due to Leviton discontinuing the OmniPro product line after buying HAI in 2019.

That's more than fair and I hope you didn't think I was in any way ungracious in my comments. Its a great at what it does and has worked rock solid for years now.

**Comment by rwagoner** [comment]
> That's more than fair and I hope you didn't think I was in any way ungracious in my comments. Its a great at what it does and has worked rock solid for years now.

We're on the same page. How do you have it deployed? Are you using it with Home Assistant?

**Comment by jlipsit** [comment]
Hi Ryan,

Thanks for the quick response. I Switched over to the DEV code (Copied over my old INI) and can see that it publishes "Locks" = see first image below.  However the locks do not appear in Home Assistant.  

In the second screen shot you can see how my two Zwave locks appear under access control in the HAI dealer access software.  There should be 2 actual locks that are named ("S Garage Entry" and another that is "N Garage Entry") - not to be confused with the FLAGS that I created to view the status of these locks in HA that are named "SGarLock" and "NGarLock".

Let me know if you need me to try something else.

![OmniLinkBridge-DEV](https://github.com/excaliburpartners/OmniLinkBridge/assets/155367039/fab0c8e8-4193-42ab-beb5-cff750d26207)
![HAI Locks](https://github.com/excaliburpartners/OmniLinkBridge/assets/155367039/c3595e80-7243-4757-ad29-b1347b6d64ed)

**Comment by rwagoner** [comment]
The issue was I forgot to include the line to publish the Home Assistant discovery information for the locks to MQTT. I've pushed another set of changes to dev to include verbose lock logging. Please add `verbose_lock = yes` to your ini file. You should see LockStatus on the console at startup and when the lock changes state. That will help track down further issues as we'll know if OmniLink Bridge is seeing the status correctly from the controller.

**Comment by jlipsit** [comment]
Getting very close  ;-)

Working now however the lock STATUS is backward (inverted) in Home Assistant. 

The actual lock is LOCKED but in HA it displays as unlocked. 
In my example images below... I LOCKED the South Garage Lock, however the status in HA shows unlocked when the physical lock is locked.

![Status Lock](https://github.com/excaliburpartners/OmniLinkBridge/assets/155367039/ce2fda73-87e8-4bcf-9eb1-2072fb238fde)

![Lock Status log](https://github.com/excaliburpartners/OmniLinkBridge/assets/155367039/e2f0b4ab-77a7-4f67-929d-c8d3d12ba385)

![Lock StatusBridge](https://github.com/excaliburpartners/OmniLinkBridge/assets/155367039/e1371737-e644-4cb4-9d4b-7113abfea471)

**Comment by rwagoner** [comment]
Please add `verbose_lock = yes` to the ini file and see if it's also inverted on the OmniLink Bridge console output. I want to confirm which side is being inverted. Controller to OmniLink Bridge or OmniLink Bridge to Home Assistant.

**Comment by jlipsit** [comment]
I did add "verbose_lock = yes" and the last image above / below is from the console output.  let me know if you need anything else.

![Lock StatusBridge](https://github.com/excaliburpartners/OmniLinkBridge/assets/155367039/42321d5e-918c-434f-b83e-aee3e5e7b7f2)

**Comment by jlipsit** [comment]
Sorry - I did have Verbose set but I did not grab the correct entity in the screenshot.  Here is a video that I hope will clarify what is happening. I hope this helps. Let me now.


https://github.com/excaliburpartners/OmniLinkBridge/assets/155367039/ac1c782e-e98b-48c6-b19e-a0b82bdb2e44

**Comment by rwagoner** [comment]
Thanks for the video! I read through the Omni-Link II protocol documentation and found that 0 is locked and not 1. I've fixed the inverted state and also hooked up the LockStatus line. Give it a try and hopefully we got it.

**Comment by jlipsit** [comment]
Works like a charm!  Thank you so much.  Did you get the email I sent via your consulting web form? Please let me know.

**Comment by rwagoner** [comment]
@jlipsit Glad to hear it's working! I just found the email amongst spam and sent you a response.
