### ISSUE TITLE
Time sync and time zones?

### ISSUE THREAD

**Issue by dlmorgan999** [excaliburpartners/HAILogger#58]
I've been using this plugin for a while now with Home Assistant, and it works great!  Thanks so much for providing it.  Having said that, I have one question.  I have time sync enabled and it's working, but as mentioned in the documentation, it's setting the time to UTC rather than local.  Is there any way to fix that - either in this app or on the Omni?

**Comment by rwagoner** [comment]
Are you using the Home Assistant Add-on or running the docker container?

**Comment by dlmorgan999** [comment]
I'm running the Docker container.  I only just discovered the Add-on earlier this morning.

**Comment by rwagoner** [comment]
Ensure the time in the docker container is the local time. The OmniLinkBridge readme shows mapping /etc/localtime:/etc/localtime:ro, which will set the docker container to the same timezone as your host.

**Comment by dlmorgan999** [comment]
Ah - good call.  I just checked, and time on my Docker VM is currently UTC.  I don't know how I hadn't noticed that before, but thanks for the pointer!
