### ISSUE TITLE
Support for HAI HiFi Audio?

### ISSUE THREAD

**Issue by tonynogs** [excaliburpartners/HAILogger#59]
Hello, love this. Any plans to add support for HAI HiFi Audio system that's integrated into OmniPro?

**Comment by rwagoner** [comment]
I've added audio support to the dev branch and dev tagged docker container. At this time there isn't a way to run the dev build if you are using the Home Assistant add-on version. Unfortunately, I don't have any audio zones so I'm unable to verify if it works. Please let me know if you find any issues.

**Comment by tonynogs** [comment]
I'm running OmniLinkBridge via HACS installation on HA running on a RaspberryPi. I'm sort of a rookie, so not sure this is the same as what you mention above (dev branch). Is there some way I can check this, or load the dev build?

**Comment by enry86cami** [comment]
hello, I've installed omnilink bridge with docker-compose and I have HIFI2 4x4... So now I with the latest version I will see the audio zones?

**Comment by rwagoner** [comment]
> hello, I've installed omnilink bridge with docker-compose and I have HIFI2 4x4... So now I with the latest version I will see the audio zones?

Yes in theory if you are running the `excaliburpartners/omnilink-bridge:dev` docker container.

**Comment by enry86cami** [comment]
In my docker-compose.yml I use: image: excaliburpartners/omnilink-bridge

**Comment by rwagoner** [comment]
> I'm running OmniLinkBridge via HACS installation on HA running on a RaspberryPi. I'm sort of a rookie, so not sure this is the same as what you mention above (dev branch). Is there some way I can check this, or load the dev build?

With the Home Assistant Add-on once I release a version all users are notified to update. I'd prefer not to release this until I have a few testers confirm it works. To test the dev build you would run the `excaliburpartners/omnilink-bridge:dev` docker container on your Windows or Linux system.

**Comment by rwagoner** [comment]
> In my docker-compose.yml I use: image: excaliburpartners/omnilink-bridge

Just add `:dev` to the end.

`image: excaliburpartners/omnilink-bridge:dev`

**Comment by enry86cami** [comment]
> > In my docker-compose.yml I use: image: excaliburpartners/omnilink-bridge
> 
> Just add `:dev` to the end.
> 
> `image: excaliburpartners/omnilink-bridge:dev`

Thanks...
Do you suggest adding the ":dev" in my docker-comoose.yml and After upating doing " docker-comose pull" or vice versa?

**Comment by rwagoner** [comment]
> Thanks... Do you suggest adding the ":dev" in my docker-comoose.yml and After upating doing " docker-comose pull" or vice versa?

Correct. Update the docker-compose.yml then run `docker-compose pull` and lastly `docker-compose up -d`, which will restart the container in the background with the latest pulled version.

**Comment by enry86cami** [comment]
> > Thanks... Do you suggest adding the ":dev" in my docker-comoose.yml and After upating doing " docker-comose pull" or vice versa?
> 
> Correct. Update the docker-compose.yml then run `docker-compose pull` and lastly `docker-compose up -d`, which will restart the container in the background with the latest pulled version.

Done,
Now, for each audio zone I see:
-on/off
-mute
-select source
-volume

Everything works apart the selection of the source....

**Comment by tonynogs** [comment]
> > I'm running OmniLinkBridge via HACS installation on HA running on a RaspberryPi. I'm sort of a rookie, so not sure this is the same as what you mention above (dev branch). Is there some way I can check this, or load the dev build?
> 
> With the Home Assistant Add-on once I release a version all users are notified to update. I'd prefer not to release this until 

After a lot of experimentation trying to ger the "dev" version running on Docker, we have success! I now see my audio sources and zones, so I can assume it's detecting them and working. I have no idea how to test it any further... but from where I sit, the dev version is working! This from my log file:

2024-05-01 12:12:08 2024-05-01 19:12:08 [OmniLinkBridge.Modules.LoggerModule DBG] Controller has 1 areas, 18 zones, 6 units, 0 outputs, 0 flags, 2 thermostats, 0 locks, **3 audio sources, 6 audio zones**

EDIT: Ok, further testing has determined that all functions are operational (Volume up/down, MUTE, on/off, and source select) 

BTW, I am running the HAI HiFi original hardware... not the HiFi2. 

Can't wait for the HA add-on release! Thanks for doing this!

**Comment by tonynogs** [comment]
> > > In my docker-compose.yml I use: image: excaliburpartners/omnilink-bridge
> > 
> > 
> > Just add `:dev` to the end.
> > `image: excaliburpartners/omnilink-bridge:dev`
> 
> Thanks... Do you suggest adding the ":dev" in my docker-comoose.yml and After upating doing " docker-comose pull" or vice versa?

I think I have OmniLinkBridge properly running in Docker now, but I'm not sure how to access the docker-compose.yml and add :dev to the end of excaliberpartners/omnilink-bridge:latest.

Any ideas?

**Comment by rwagoner** [comment]
@enry86cami I pushed a new dev docker build that fixes the source select and a few other issues @jlipsit found. Assuming the feedback is good I plan to release 1.1.16 tomorrow.

**Comment by enry86cami** [comment]
> @enry86cami I pushed a new dev docker build that fixes the source select and a few other issues @jlipsit found. Assuming the feedback is good I plan to release 1.1.16 tomorrow.

now the source selection works! many thanks

**Comment by rwagoner** [comment]
Version 1.1.16 with audio support has been released. You should see an update for the OmniLink Bridge Home Assistant add-on available.
