### ISSUE TITLE
Can't update to 1.1.15.2

### ISSUE THREAD

**Issue by tonynogs** [excaliburpartners/HAILogger#60]
Is anyone else having trouble getting it to update from within HA? It won't work for me. 

When I click UPDATE, it just stalls out and there is no change, still have this message: 

"You have 1.1.14.1 installed. Click update to update to version 1.1.15.2"

**EDIT: Restarting HA from the Developer Tools solved it!**

**Comment by rwagoner** [comment]
Glad to hear you got it resolved!
