### ISSUE TITLE
Latest Upgrade broke Addon

### ISSUE THREAD

**Issue by michae1a1ee** [excaliburpartners/HAILogger#64]
I can't seem to stop the OmniLinkBridge after what appears to be a failed update.
I've restarted HA, shut it down, can't see to get it to update, uninstall, anything.  What do you suggest?

![image](https://github.com/excaliburpartners/OmniLinkBridge/assets/163686604/fcf288db-48a6-45e8-8a52-59500410f333)

**Comment by rwagoner** [comment]
I found another user of a different add-on with the same issue. It looks like the fix was to restart the machine (not just Home Assistant) and uninstall / install the add-on.

https://github.com/sabeechen/hassio-google-drive-backup/issues/992

**Comment by michae1a1ee** [comment]
I'm running HAOS in an Oracle VM VirtualBox.  I've already shut it down completely and restarted.

**Comment by michae1a1ee** [comment]
But thanks to your advice, I re-visited this.  I did a Shutdown from the HA GUI.  That also closed down the VM, and now that I've restarted HA I was able to uninstall the Addon that was acting up.  Good suggestion.

**Comment by michae1a1ee** [comment]
Removing the OmniLinkBridge has left me with all the Omni devices/entities on the Home Assistant Overview dashboard.  How do I get rid of those now that the Addon is uninstalled?  I'm surprised the items pertaining to the removed Addon are still there.

**Comment by rwagoner** [comment]
The devices/entities are not linked to the add-on. They are discovered through MQTT. If you are planning to reinstall the add-on, there is no need to cleanup the entities first. If you do want the entities removed, you would need to delete the homeassistant/*/omnilink MQTT entries using a tool like MQTT Explorer.

**Comment by michae1a1ee** [comment]
Thank you @rwagoner
That is useful information.  I see now what you're talking about with the devices being discovered through MQTT.  Today I found that OmniLinkBridge 1.1.18.1 WAS finally installed.  I've been able to get HA back to a normal state, but ultimately I'm going to need to use your advice to get rid of entities and will look into MQTT Explorer.  OmniLinkBridge is constantly failing to connect to my Omni panel (hardware issue, not the Add-on's fault) so I'm going to have to replace it and scrub it from HA.

![image](https://github.com/excaliburpartners/OmniLinkBridge/assets/163686604/ab2bf383-e581-4325-abc3-7798ec6bf575)

**Comment by michae1a1ee** [comment]
I figured out where to get MQTT Explorer as an HA Add-on.  Looks like a useful tool.
I see what you're saying with the MQTT omnilink entries... there are a LOT of them, both under "homeassistant" and the "omnilink" top level folders, if that's the right way to describe what I'm seeing in MQTT Explorer.
![image](https://github.com/excaliburpartners/OmniLinkBridge/assets/163686604/e9ce9738-2a5c-4a52-9fa6-b3254926f308)

**Comment by rwagoner** [comment]
Since OmniLink Bridge looks to be the only MQTT integration you have, you can just delete the top level homeassistant folder and omnilink folders. Once you restart Home Assistant the MQTT devices should disappear.

When OmniLink Bridge starts up, it publishes all discovery topics and clears any that are no longer configured on the OmniPro controller. It should self correct after you connect OmniLink Bridge to the new controller. You would just need to restart Home Assistant.

On your disconnecting issue, the OmniPro network port can be overwhelmed by broadcast traffic on the network. I had to place mine on a separate VLAN / subnet. If you look on Cocoontech you can find posts from others with similar issues. You could verify by isolating the OmniPro controller and OmniLink Bridge to a switch and see if the connection issues disappear.

**Comment by michae1a1ee** [comment]
Thanks Ryan.  I've actually got my X10-protocol light switches setup in Home Assistant through the "X10 MQTT Gateway" Add-on using a CM11A interface to make at least my lighting a little more reliable.  So with those lights configured in my configuration.yaml file I'm guessing I need to keep MQTT running, and be careful to only remove "omnilink" references through MQTT Explorer.

I figured what you said in your second paragraph must be the case because in my own situation, over the last couple months that I've been playing with Home Assistant and OmniLinkBridge, I've found that sometimes when I restart Home Assistant the number of found Omni devices (or "entities" actually) might change.  Right now for instance my Home Assistant Overview page is only showing 14 items pertaining to the Omni Pro II (all unavailable).  I presume this is because the communication with the OP2 panel has failed to read all the devices, zones, etc. off the panel.  When you mentioned connecting to "the new controller" I'm reading this to mean if I were to find a replacement OP2 panel?

Regardless, I am aware of Cocoontech, and have been reasonably active on those forums.  I know about the the switch or hub being placed in front of the OP2, and have tried that, as well as an old 100Mbps router that was setup to put the OP2 on a different VLAN than the rest of my house, changing the IP address set on the OP2 panel itself.  I haven't had much luck with any of these solutions, at least not for any period of time.  When it did work I was excited to see everything show up in Home Assistant, but the connection issues soon returned as the Ethernet port became overwhelmed.  At one point I had a pretty full list of OP2 entities in Home Assistant thanks to the add-on, but as you've described, upon a later reboot where the OP2 was not communicating well, I lost the long list when the discover process you're talking about would have been re-initialized.

![image](https://github.com/excaliburpartners/OmniLinkBridge/assets/163686604/1d4f1e77-2673-454b-8a49-e5c06be394db)

**Comment by rwagoner** [comment]
> When you mentioned connecting to "the new controller" I'm reading this to mean if I were to find a replacement OP2 panel?

Yes I was referring to a replacement OP2 panel.

>  I know about the the switch or hub being placed in front of the OP2, and have tried that, as well as an old 100Mbps router that was setup to put the OP2 on a different VLAN than the rest of my house, changing the IP address set on the OP2 panel itself.

It sounds like you have exhausted all options besides replacing the panel. OmniLink Bridge uses the official HAI C# SDK for the low level communication with the panel. The entities go to unavailable in Home Assistant when OmniLink Bridge looses connection with the panel.

**Comment by michae1a1ee** [comment]
Ryan, can you verify if you know, that there are no OP2 panels ever made with anything other than a 10Mbps Ethernet port (nothing newer), correct?

**Comment by rwagoner** [comment]
No, not that I am aware. I bought mine back in 2012 when I was deciding between the HAI OmniPro II and Elk M1. I've been casually looking at the Elk E27 Alarm Engine that was just released. However I haven't seen any of the API documentation to know how feasible it will be to build an integration with Home Assistant. For now I plan to keep using the OmniPro II. The system has been reliable for me since I placed it on it's own VLAN. I have it connected to an HP 2530-24G-PoE+ switch. The link comes up as 10 half duplex.

**Comment by michae1a1ee** [comment]
I'm considering rewiring all my physical wired zones (motion sensors, etc.) from the OP2 over to a Konnected board.  Currently they can get the zones into HA via Smartthings, but I understand they are working on native HA support.  Really, I'm trying to look  into all options, but haven't made a decision yet.  With the OP2 I'm not confident in my particular panel which I got in 2003.

**Comment by rwagoner** [comment]
I have two SmartThings hubs that I bought back in 2017. Before MQTT I had written the OmniLink Bridge WebAPI to talk to the SmartThings hub over the local LAN. However the hub sends everything to the SmartThings cloud and at times their cloud would have delays or outages. I haven't used them since switching to Home Assistant and writing the MQTT bridge.

I've looked at the Konnected boards before, but they don't have a UL lisiting for burglary or fire. I have System Sensor smoke detectors in the house connected to the OmniPro II. I do see Konnected has a direct integration with Home Assistant using ESPHome firmware. I have a number of ESP8266 and ESP32 modules running ESPHome and it's been great.
https://support.konnected.io/add-a-konnected-device-to-home-assistant-with-esphome

**Comment by michae1a1ee** [comment]
And I just found this:  https://www.home-assistant.io/integrations/konnected/
while you were writing back.  So I don't know how new that integration is, but it seems like they are actively working on it.  I would like to avoid getting into SmartThings at this point in time as I'm not a current user of it; installed it and never really needed to use it.

I'm glad you brought up the burglary and fire comment; security and smoke detectors are two of the items I'm still looking into in regards to whether a Konnected board could be a viable replacement for the OP2, while moving all the automation/programming logic functions of the OP2 over to HA.  I guess from what you're saying, Konnected will not be able to make use of our OP2 connected smoke alarms, sirens, etc.?  I'll look into this.

**Comment by rwagoner** [comment]
If you have smoke detectors, I would recommend using a UL listed fire panel. Most detectors, even with integrated sounders, require the panel to activate the sounder by reversing polarity on the loop. The exception, which I haven't tested it standalone, is the System Sensor COSMOD2W interface module. I am using this to interface 2-wire smoke detectors and combo smoke/carbon monoxide detectors with the OmniPro II panel. It breaks out the smoke, co and maintenance triggers to separate zones.

Alarm panels that integrate with Home Assistant are limited. The DSC PowerSeries (discontinued in 2021) and Ademco Vista integrate using Envisalink. I recall the Vista had some limitations on zone restore notification as they were emulating the keypad bus. I've heard good things about the Elk M1, however I'm not sure I would buy one with the new Elk E27 being released. The catch is the Elk M1 already has a Home Assistant integration and the Elk E27 does not. Additionally Elk doesn't appear to be all that open to home owners getting access to the configuration software and manuals.

**Comment by michae1a1ee** [comment]
This is really useful information Ryan.  I've looked at the Elk M1 briefly, but if the M1 were the OP2 replacement that Elk would tell you it is, why wouldn't all the HAI customers just have moved over to Elk?  I haven't gotten the impression from them that it does everything the OP2 does, and it's not an inexpensive system.  I think that's why I've been mainly looking at parsing out the duties of the OP2 and considering Konnected.  What you're bringing to light is that Konnected may only be able to properly deal with wired motion detectors, door and window sensors.

**Comment by rwagoner** [comment]
It probably comes down to Elk being not being positioned to sell direct to end users. I'm sure you would find security installers recommending Elk to replace a failed OmniPro panel. I debated between the two brands when I bought my OmnIPro 2. The Elk M1 supports integration with Lutron RadioRA 2 so both would have satisfied my requirements. 12 years later I personally feel the M1 is dated. I'm waiting to see how the Elk E27 plays out.

The Konnected boards also seem expensive for $229 for 12 zones ($19/zone). Your essentially paying for R&D, as the ESP chip costs under $10. If these were in the $100-150 range I would have a few today for various purposes. If you need to replace an OmniPro 2 with zone expander (32 zones) the Elk pricing starts to look much more comparable.

With Konnected you are relying on the full Home Assistant stack, which has way more complexity and potential failure points. This may or may not be an issue for you. If you want a light to turn on when motion detected this works well. With life safety, like a smoke detector, I want this done in hardware. Additionally Konnected doesn't support end of line resistors, which means you have no tamper / fault detection.

**Comment by michae1a1ee** [comment]
You've given me a lot to think about and you're making me wish my OP2 Ethernet port was working properly so I could use your HA Add-on instead.

**Comment by rwagoner** [comment]
> You've given me a lot to think about and you're making me wish my OP2 Ethernet port was working properly so I could use your HA Add-on instead.

In PC Access do you have any Automation rules defined? If so have you tried deleting them all?

**Comment by michae1a1ee** [comment]
In PC Access I have 75 line items on the Automation tab.  I have never tried deleting all of them - I figure that is basically all the programming that was done on the unit by the installer many years ago.  The top of the interface shows Available Program Lines: (1425/1500), so I never felt like my system was overly utilized based on having so little code added to the panel.  Are you suggesting the automation programming has something to do with the Ethernet port issues??

**Comment by rwagoner** [comment]
My understanding is if the automation rules form a loop it can exhaust the controller resources. You can delete the automations, write to controller: programs and see if it changes anything. If not, close with the file without saving, open it again, and write to controller: programs to load the automations back.

**Comment by michae1a1ee** [comment]
Interesting.  I might have to try that then.
I'll need to setup a laptop with Dealer PC Access and Serial connectivity as I obviously haven't been able to reliably connect to the OP2 panel via PC Access through Ethernet for a while.

**Comment by rwagoner** [comment]
If it connected before in PC Access and you know you haven't made any changes to cause the ethernet issue I would try "Reset System RAM" from the console 9 Setup -> 1111 (Installer Code) -> # (Installer Menu) -> 6 Misc -> "Reset System Ram" -> 1

https://www.alarmhow.net/manuals/HAI/Omni%20Pro%20II/OmniPro%20II%20v2.16%20Installation%20Manual.pdf
Page 53
`Select the 1 (YES) key to cause all of the system RAM to be reinitialized. The time, date, and event log will be cleared. Other
volatile memory locations will also be reinitialized. The system RAM should only be reset if the system is acting strangely and
memory corruption is suspected. Resetting the system RAM will not reset any setup items stored in EEPROM. `

**Comment by rwagoner** [comment]
Assuming you have a PC Access backup you could "Reset System EEPROM" to clear the setup, names, and all programs. If it was an automation causing the issue PC Access would then be able to connect over ethernet. You would need to reconfigure the IP Address and Encryption Keys, if they were changed from the defaults. Worst case you would need to get your laptop with serial out to restore the config.

I would try both of these before swapping the board or moving to an alternative solution. You might get luckily and find it's not a hardware issue.

**Comment by michae1a1ee** [comment]
> If it connected before in PC Access and you know you haven't made any changes to cause the ethernet issue I would try "Reset System RAM" from the console 9 Setup -> 1111 (Installer Code) -> # (Installer Menu) -> 6 Misc -> "Reset System Ram" -> 1
> 
> https://www.alarmhow.net/manuals/HAI/Omni%20Pro%20II/OmniPro%20II%20v2.16%20Installation%20Manual.pdf Page 53 `Select the 1 (YES) key to cause all of the system RAM to be reinitialized. The time, date, and event log will be cleared. Other volatile memory locations will also be reinitialized. The system RAM should only be reset if the system is acting strangely and memory corruption is suspected. Resetting the system RAM will not reset any setup items stored in EEPROM. `

This one I could check right away, so I did.  My Installer - Misc menu doesn't have an option to Reset System Ram, or anything related to RAM for that matter.  Strange.  So much for the low hanging fruit that I was going to try first.  As for your questions about programming, I don't really see it as the issue.  The only programming line changes I've made have been to remove/add users.  The code has largely remained the same and untouched for years.

**Comment by rwagoner** [comment]
Just to confirm ,you hit # after entering the installer code. The 6 Misc is different under the # Installer sub menu.

**Comment by michae1a1ee** [comment]
> Just to confirm ,you hit # after entering the installer code. The 6 Misc is different under the # Installer sub menu.

I had been using a Setup Code that I thought was an Installer Code forever!  Checked some notes I have and found I had a different Installer recorded there.  So I've done the RAM reset, re-entered the time and date from the keypad and things are back to how they were.  Initial PING test was still at least 75% packet loss.  I'll take a closer look at it tomorrow.  I left the omnilinkbridge.exe app running in a command prompt window to monitor what it's displaying.

**Comment by michae1a1ee** [comment]
Ryan, I was re-reading your comments pertaining to the reasons for a dedicated hardware solution for security/safety items like smoke detectors.  After some research and investigation, it seems that the smoke detectors I have connected to my OP2 might be low voltage models (side note - they appear to be type that Konnected seem to require).  I got the impression from our conversation that these were not your preference, which makes me wonder, are your OP2-connected smoke detectors different than low voltage models?  I've attached a picture of my basement ceiling.  The smoke detector on the left is one of the original "dumb" builder smoke detectors, and the one on the right is one of the smoke detectors installed by my OP2 installer which I believe is wired back to the OP2 panel with Cat5 cable.
![smokedetectors](https://github.com/excaliburpartners/OmniLinkBridge/assets/163686604/18894bc6-d89a-4386-abc8-7f903daf5390)

**Comment by rwagoner** [comment]
I only have low voltage System Sensor 2-wire smoke detectors with the COSMOD2W interface module. I'm relying on the OmniPro II, which is a UL listed panel for residential fire, to sound the fire alarm. The bedrooms have the 2WTA-B photoelectric with rate of rise detectors and the hallways have the COSMO-2W CO/smoke detectors.

The OmniPro II is connected to the COSMOD2W interface module with zones for fire, co, and maintenance. Each zone is terminated with an EOL resistor. I also have outputs configured for smoke reset, smoke trigger, and co trigger. If the module looses power, a detector is pulled from the ceiling, etc the OmniPro II zone will go into a trouble state.

When a smoke detector is triggered the sounders on all detectors go off as well as the OmniPro II siren. To clear the alarm, I have a button programmed to activate the smoke reset output to power cycle the System Sensor interface module.

With Konnected I wouldn't be able to achieve the above without creating automations in Home Assistant. At minimum I would need to have some safeguards around ensuring Home Assistant is running. Without the support for EOL resistors I wouldn't know if the System Sensor interface module had a fault as the zones only have two states and not three.

**Comment by michae1a1ee** [comment]
Your commentary has really got me thinking about the value of having a dedicated security panel.  I think I had probably forgotten my own reasons for having an OP2 in the first place.  Having said that, if you were in my position, with an OP2 that you couldn't reliably communicate with through Ethernet, would you consider buying this combination:
1. Honeywell Vista 20P panel
2. EyezOn EnvisaLink 4 to add Ethernet and Home Assistant integration

**Comment by michae1a1ee** [comment]
I've been doing my research on security system replacements, keeping in mind what you've said about dedicated wired security systems, UL listing, smoke detectors, etc.
Have you seen this EyezOn Uno panel?  https://www.eyezon.com/uno.html
Would love your thoughts.

**Comment by jlipsit** [comment]
**"Having said that, if you were in my position, with an OP2 that you couldn't reliably communicate with through Ethernet...."**

Hi Mike,  I read that you have issues with the ethernet on the OP2 and I saw that you have done some troubleshooting.  I had the same problems that got worse over time and mine was solved by connecting the OP2 to a "dumb" switch.  **You may try one final troubleshooting step to rule this out. Find an old router and connect ONLY your PC and OP2 to it - nothing else.** Then use HAI PC Access to connect and monitor the status. (Assuming you cannot do that now over Ethernet).  If it works, then the Ethernet port is not bad.

This kicked by butt for years until i figured this out. I have a Ubiquity Unifi network with several switches and what fixed it for me was plugging the OP2 into the UDMPro and also setting the port to 10 HDX.  Pretty sure all the (multicast ?) traffic on the network carried by these switches overwhelm these old ports. (I also had the exact same problem with my old Russound amplifier.) Both were solved by moving the connection. 

![Switches](https://github.com/excaliburpartners/OmniLinkBridge/assets/155367039/506c51f9-6981-472c-9510-b74f24404be1)

**Comment by rwagoner** [comment]
@jlipsit I have essentially the same setup with mine. 10M half duplex port on a managed switch VLAN. This is the ONLY device on this subnet / VLAN besides the router. The half duplex is severely limiting as the controller cannot send/receive data at the same time. When collision occurs the controller / switch have a random backoff time and try again. I'm assuming the buffer is non existent so data is lost resulting in connection issues. The Lutron RadioRA2 main repeater is 10M full duplex and I don't have any of these issues.
```
  Totals (Since boot or last clear) :
   Bytes Rx        : 322,326,336          Bytes Tx        : 2,382,932,213
   Unicast Rx      : 4,103,572            Unicast Tx      : 4,058,419
   Bcast/Mcast Rx  : 0                    Bcast/Mcast Tx  : 15,955,037
  Errors (Since boot or last clear) :
   FCS Rx          : 255                  Drops Tx        : 65
   Alignment Rx    : 0                    Collisions Tx   : 1258
   Runts Rx        : 0                    Late Colln Tx   : 369
   Giants Rx       : 0                    Excessive Colln : 0
   Total Rx Errors : 1611                 Deferred Tx     : 1126
```

**Comment by rwagoner** [comment]
> I've been doing my research on security system replacements, keeping in mind what you've said about dedicated wired security systems, UL listing, smoke detectors, etc. Have you seen this EyezOn Uno panel? https://www.eyezon.com/uno.html Would love your thoughts.

Great find! It looks like they are building a replacement for the DSC PowerSeries with a built-in network port. I don't see anything about a UL listing, but you also have builder smoke detectors, so this might not be an issue for you. I do see it supports zone resistors, which is great. I'm also making the assumption it will work with the current Home Assistant EyezOn integration.

**Comment by michae1a1ee** [comment]
@jlipsit Thank you for weighing in on this discussion with Ryan and I, much appreciated.  I wanted to clarify a few things or add some more details:
My OP2 ethernet port is not dead.  I am able to get PING response *occasionally*.  Right at this moment doing a few PING tests I got 50% loss, 50% loss, 75% loss, 100% loss, 50% loss.  Not good, but the PC I'm writing this from was able to make some communication with the OP2 panel through my network, just not consistently.
I've tried a few changes with my network over time.  I put a 100Mbps router in front of the OP2 and segmented the OP2 from the rest of my network with the suggestion/assistance of a senior member on CocoonTech.  That didn't work for very long before the OP2 returned to being hardly accessible.  I changed things back to the simpler setup I had before, and right now I have a Netgear EN104TP 10Mbps hub (that I bought for this purpose) placed between the OP2 and my Asus Gigabit router.  The Asus router reports the LAN Port2 (that runs to the Netgear hub) as having a Link State of "10 Half Duplex".  I'm not setting that; that's what the router is reporting.  I obviously don't have as fancy a network setup like yours (nice Unifi setup you've got btw!) but it would seem to me that not having a network appliance that can explicitly set the Link State may be a shortcoming in getting the OP2 ethernet to work consistently.  The 10Mbps hub seemed like a good idea but apparently not enough to calm the traffic hitting the OP2 indefinitely.

**Comment by rwagoner** [comment]
A hub has a single collision domain for all ports and essentially lets all devices hear each other. A switch has a collision domain per port along with port buffers. On a unmanaged switch multicast traffic is treated like broadcast and sent out all the ports. You need a layer 2 managed switch with IGMP snooping enabled to filter multicast to only ports that subscribe to the multicast group. You can also use a router to create a new layer 3 segment thus isolating you from the layer 2 multicast/broadcast domain.

**Comment by michae1a1ee** [comment]
> > I've been doing my research on security system replacements, keeping in mind what you've said about dedicated wired security systems, UL listing, smoke detectors, etc. Have you seen this EyezOn Uno panel? https://www.eyezon.com/uno.html Would love your thoughts.
> 
> Great find! It looks like they are building a replacement for the DSC PowerSeries with a built-in network port. I don't see anything about a UL listing, but you also have builder smoke detectors, so this might not be an issue for you. I do see it supports zone resistors, which is great. I'm also making the assumption it will work with the current Home Assistant EyezOn integration.

Yes, so EyezOn has so far told me that the Uno IP Panel has a built in EnvisaLink 4 (ELV4) module, so that provides Home Assistant integration, as well the panel having Alexa and Google Home integration apparently.  Like you mentioned, it seems to be designed as a DSC Power Series drop-in replacement.  *If* I have to abandon the OP2, after our conversation I've been thinking the best route would be a old dedicated security panel with an ELV4 module added to make it smart and get it to talk to Home Assistant.  The two best-fit compatible panels would be a DSC Power Series 1864 or a Honeywell Vista 20P.  The 1864 has been discontinued for a while and from what I can tell only available on the used market.  The Vista 20P is a good option too, it is still available to be purchased and I'm fairly pleased with what I've read about it.

BUT - in looking into this EyezOn Uno IP Panel, I'm seriously questioning if this might be the smarter route...  a newly designed board with wired zones and much higher total zone capacity, 100Mbps ethernet on-board, the ELV4 and therefore Home Assistant support built-in, web based GUI programming rather than only through an old number keypad.  The Uno has support to add wireless zones for less important sensors, LTE cellular communications backup if I want to pay for it, free Android/iOS apps and web portal for control.  It's definitely a more modern approach to doing the old security panel.  I'm still trying to get a definitive answer on UL Certification for the panel, but in regards to the smoke detectors, I would expect the same detectors I have wired to the OP2 should be able to be connected to this panel as well, I hope, or at least be able to use the wiring I have run to the smoke detector locations.

I appreciate the feedback you've provided on this and everything else.  Seems like you think the Uno might a good option; I'm going to keep trying to gather information on it to get all the unknowns ironed out.

**Comment by rwagoner** [comment]
At my last house, before I swapped to the OmniPro II, I had an First Alert 148CP. This was essentially a rebranded Vista 20P. It was a good alarm panel. The wireless sensor capabilities are ahead of what is available on the OmniPro II. There is no support for automations and it's essentially an input only board. You will want to do any logic in Home Assistant and implement outputs with a different product like a Sonoff 4CH relay module.

I didn't know about the EnvisaLink module, or it might not have been out, at that time. My understanding is it's emulating a keypad. I've read through the [Home Assistant Envisalink documentation](https://www.home-assistant.io/integrations/envisalink/) before and Honeywell has two limitations over DSC.

`zonedump_interval  This is an interval (measured in seconds) where Envisalink will dump out all zone statuses. This is required for Honeywell systems, which do not properly send zone closure events. DSC boards do not technically need this.`

`invoke_custom_function: Invokes a custom PGM function. DSC alarms only`

**Comment by michae1a1ee** [comment]
> A hub has a single collision domain for all ports and essentially lets all devices hear each other. A switch has a collision domain per port along with port buffers. On a unmanaged switch multicast traffic is treated like broadcast and sent out all the ports. You need a layer 2 managed switch with IGMP snooping enabled to filter multicast to only ports that subscribe to the multicast group. You can also use a router to create a new layer 3 segment thus isolating you from the layer 2 multicast/broadcast domain.

Would a Netgear GS105Ev2 fulfill this requirement?  I don't know anything about managed switches so it would be something I'd have to look into to accomplish what you said, "IGMP snooping enabled to filter multicast to only ports that subscribe to the multicast group"
Netgear GS105Ev2
https://www.amazon.ca/NETGEAR-GS105Ev2-Gigabit-Lifetime-Protection/dp/B00HGLVZLY?th=1

or even cheaper:
D-Link DGS-1100-05V2
https://www.amazon.ca/D-Link-Features-Diagnostics-EasySmart-DGS-1100-05V2/dp/B08MV9315K

**Comment by michae1a1ee** [comment]
Guys, need some help.
I got the D-Link DGS-1100-05V2 I mentioned before.  Managed 5-port switch, for the purpose of putting it in front of the OP2.  I've got it all connected, made changes to the eth4 port where I've plugged the OP2 into (made it 10M half duplex), turned on IGMP snooping.  These changes from default settings haven't yet made any difference with the connectivity to the OP2 panel.  I know you also said I needed to add a VLAN.  I'm not familiar with this process but I've been reading about and have tried a Port-based VLAN, then a Management VLAN.  The second attempt made me loose connection to the Switch and I had to do a complete hard reset to get back into it.  The Switch IP address has been changed to 192.168.1.2 so that it's available from my LAN.  The OP2 is 192.168.1.3.
Can you make any suggestions as to what I need to try?

![image](https://github.com/excaliburpartners/OmniLinkBridge/assets/163686604/21ac8c14-dbf0-44cd-92db-65ac3fd0aefd)

**Comment by rwagoner** [comment]
I just encountered this same issue after years of it working with no changes to my network. It turns out the OmniPro has issues with gigabit switches and putting a 10/100 switch in the middle resolves the packet loss.

https://cocoontech.com/threads/omni-iie-network-repair.31625/post-266900
