### ISSUE TITLE
MQTT autodiscovery not working for Alarm Panel

### ISSUE THREAD

**Issue by 5aji** [excaliburpartners/HAILogger#8]
Hi,
First, thanks for your hard work in making this software. It works great so far, no major issues.
However, there is one problem. The autodiscovery is not working for the alarm panel. I can't seem to find the discovery config being posted in the `homeassistant` topic. I see that there is code for it [here](https://github.com/excaliburpartners/OmniLinkBridge/blob/a9c52b433f1335d638b9d8f9ff6398c35e9d2f8d/OmniLinkBridge/MQTT/MappingExtensions.cs#L18). But i can't seem to see it in my broker. Everything else works fine.

**Comment by rwagoner** [comment]
Make sure your area has a name defined in the PC Access software and isn't just AREA 1. It will only publish areas, zones, units, etc that are named.
